version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  ignore:
      - dependency-name: "brakeman"
      - dependency-name: "selenium-webdriver"
      - dependency-name: "tailwindcss-rails"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
